#!/bin/bash

BIRTHDATE="January 1, 2000"
Presents=10
BIRTHDAY= date -d "$BIRTHDATE" +%A


if [ "$BIRTHDATE" == "January 1, 2000" ] ; then
	echo "BIRTHDATE is correct, it is $BITHDATE"
else 
	echo "BIRTHDATE is incorect - please retry"
fi

if  [ "$Presents" == 10 ] ; then
	echo "I have received $ Presents presents"
else
	echo "Presents is incorrect - please retry"
fi

if [ "$BIRTHDAY" == "Saturday" ] ; then
	echo "Iwas born on a $BIRTHDAY"
else
	echo "BIRTHDAY is incorrect -please retry"
fi


SOLUTION

#!/bin/bash
# Change this code
BIRTHDATE="Jan 1, 2000"
Presents=10
BIRTHDAY=`date -d "$BIRTHDATE" +%A`


# Testing code - do not change it

if [ "$BIRTHDATE" == "Jan 1, 2000" ] ; then
    echo "BIRTHDATE is correct, it is $BIRTHDATE"
else
    echo "BIRTHDATE is incorrect - please retry"
fi
if [ $Presents == 10 ] ; then
    echo "I have received $Presents presents"
else
    echo "Presents is incorrect - please retry"
fi
if [ "$BIRTHDAY" == "Saturday" ] ; then
    echo "I was born on a $BIRTHDAY"
else
    echo "BIRTHDAY is incorrect - please retry"
fi
